# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arpit's Blog
email: arpit.b.bhayani@gmail.com
description: I am a developer, designer, thinker, analyzer, physics enthusiast and data-scientist. This is the place where I put my random throughts and my imaginations into words.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arpitbbhayani.github.io" # the base hostname & protocol for your site
img: http://arpitbbhayani.github.io/static/images/myAvatar.png

permalink: /:categories/:title.html

# Build settings
markdown: kramdown

exclude: [static/semantic/src/, static/semantic/tasks, static/node_modules]
