# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arpit's Blog
email: arpit.b.bhayani@gmail.com
description: A place where I put my random thoughts into words, my views on various things happening around the globe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arpitbbhayani.github.io" # the base hostname & protocol for your site
img: https://arpitbbhayani.github.io/static/images/myAvatar.png

permalink: /:categories/:title.html

# Build settings
markdown: kramdown

exclude: [static/semantic/src/, static/semantic/tasks, static/node_modules]
