# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arpit Bhayani | An avid programmer, passionate about code, design, startups and technology
email: arpit.b.bhayani@gmail.com
description: I am a coder, developer, designer, thinker, data scientist and physics enthusiast and this is where I put my random throughts and vague imaginations into words.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arpitbhayani.me" # the base hostname & protocol for your site
img: http://arpitbhayani.me/static/images/arpit.jpg
keywords: blog, computer science, physics, competitive programming

permalink: /:categories/:title.html
highlighter: pygments
twitter_username: arpit_bhayani

# Build settings
markdown: kramdown
exclude: [static/semantic/src/, static/semantic/tasks, static/node_modules]
gems:
    - jekyll-sitemap
blog_types:
    - techie
    - curiosity
