# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arpit's Blog
email: arpit.b.bhayani@gmail.com
description: I am a developer, designer, thinker, data scientist and physics enthusiast and this is where I put my random throughts and vague imaginations into words. You might find something really crazy in here ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arpitbbhayani.github.io" # the base hostname & protocol for your site
img: http://arpitbbhayani.github.io/static/images/myAvatar.png

permalink: /:categories/:title.html
highlighter: pygments

# Build settings
markdown: kramdown
twitter_username: arpit_bhayani
exclude: [static/semantic/src/, static/semantic/tasks, static/node_modules]
